document.getElementById('interviewForm').addEventListener('submit', async (e) => {
    e.preventDefault();

    const role = document.getElementById('role').value;
    const experience = document.getElementById('experience').value;
    const topic = document.getElementById('topic').value;

    const btn = document.getElementById('generateBtn');
    const loading = document.getElementById('loading');
    const resultDiv = document.getElementById('result');

    // UI state updates while fetching
    btn.disabled = true;
    loading.classList.remove('hidden');
    resultDiv.classList.add('hidden');
    resultDiv.innerHTML = '';

    try {
        const response = await fetch('/api/interview', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ jobRole: role, experience, topic })
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error || 'A server error occurred');
        }

        // Display the HTML generated by the Groq AI
        resultDiv.innerHTML = data.result;
        resultDiv.classList.remove('hidden');
    } catch (error) {
        resultDiv.innerHTML = `<p style="color: #ef4444; font-weight: bold;">Error: ${error.message}</p>`;
        resultDiv.classList.remove('hidden');
    } finally {
        btn.disabled = false;
        loading.classList.add('hidden');
    }
});
