export default async function handler(req, res) {
    // Only allow POST requests
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    const { jobRole, experience, topic } = req.body;
    const apiKey = process.env.GROQ_API_KEY;

    if (!apiKey) {
        return res.status(500).json({ error: 'Groq API Key is not configured in Vercel environment variables.' });
    }

    // System prompt engineered to return raw, embeddable HTML content
    const prompt = `You are an elite technical interviewer. Generate a challenging mock interview scenario for a ${experience}-level ${jobRole} focusing on ${topic}. Provide 3 specific, highly technical questions and 1 behavioral question. Format your response exactly as clean HTML snippets (using <h3>, <p>, <ul>, <li> tags). Do not wrap the response in markdown blocks. Do not include <html> or <body> tags. Just return the raw HTML content.`;

    try {
        const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: 'llama-3.3-70b-versatile',
                messages: [{ role: 'user', content: prompt }],
                temperature: 0.7
            })
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error?.message || 'Error communicating with Groq API');
        }

        // Return the clean HTML generated by Groq
        return res.status(200).json({ result: data.choices[0].message.content });
    } catch (error) {
        return res.status(500).json({ error: error.message });
    }
}
